### ISSUE TITLE
可以细说一下用法嘛

### ISSUE THREAD

**Issue by slysky5418** [CLOUDERHEM/Fucklejian-Backend#1]
可以细说一下用法嘛

**Comment by CLOUDERHEM** [comment]
cXE6MTQ4OTc4MDEzNywg5aSH5rOoZ2l0aHVi==

**Comment by CLOUDERHEM** [comment]
> 可以细说一下用法嘛

cXE6MTQ4OTc4MDEzNywg5aSH5rOoZ2l0aHVi==
